package rs.biljnaapotekasvstefan.ordertrack.model;
// Generated Jun 14, 2017 10:17:23 PM by Hibernate Tools 5.2.3.Final

import lombok.*;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import java.io.Serializable;

/**
 * AuthoritiesId generated by hbm2java
 */
@Embeddable
@AllArgsConstructor
@Getter
@Setter
@EqualsAndHashCode
@NoArgsConstructor
public class AuthoritiesId implements Serializable {

	private static final long serialVersionUID = 2106128432100052634L;
	@Column(name = "username", nullable = false, length = 50)
	private String username;
	@Column(name = "authority", nullable = false, length = 50)
	private String authority;

}
