package rs.biljnaapotekasvstefan.ordertrack.model;
// Generated Jun 14, 2017 10:17:23 PM by Hibernate Tools 5.2.3.Final

import com.fasterxml.jackson.annotation.JsonBackReference;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;

/**
 * Authorities generated by hbm2java
 */
@Entity
@Table(schema="ord", uniqueConstraints = @UniqueConstraint(columnNames = { "username", "authority" }))
@Getter
@Setter
@NoArgsConstructor
public class Authorities implements java.io.Serializable {

	private static final long serialVersionUID = -3616732086118168488L;

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "username", column = @Column(name = "username", nullable = false, length = 50)),
			@AttributeOverride(name = "authority", column = @Column(name = "authority", nullable = false, length = 50)) })
	private AuthoritiesId id;

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "username", nullable = false, insertable = false, updatable = false)
	private Users users;


}
