FROM maven:3.8.6-openjdk-11 as build
RUN mkdir /ordertrack
COPY . /ordertrack
WORKDIR /ordertrack
RUN mvn clean -DskipTests package

FROM openjdk:11-jre-slim
RUN apt-get update && \
    apt-get install -y gnupg wget curl unzip --no-install-recommends && \
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list && \
    apt-get update -y && \
    apt-get install -y google-chrome-stable && \
    CHROMEVER=$(google-chrome --product-version | grep -o "[^\.]*\.[^\.]*\.[^\.]*") && \
    DRIVERVER=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROMEVER") && \
    wget -q --continue -P /chromedriver "http://chromedriver.storage.googleapis.com/$DRIVERVER/chromedriver_linux64.zip" && \
    unzip /chromedriver/chromedriver* -d /chromedriver && \
    apt-get remove --purge --auto-remove -y curl && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/cache/apt/* && \
    rm /etc/apt/sources.list.d/google-chrome.list
ENV WEBDRIVER_PATH=/chromedriver/chromedriver
RUN mkdir /ordertrack
WORKDIR /ordertrack
COPY --from=build /ordertrack/target/*.jar app.jar
EXPOSE 8080
CMD ["java","-jar","app.jar"]